version: '3'

services:
  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker2020
      POSTGRES_DB:  database
    ports:
      - "5432:5432"
    volumes:
      - /home/peidrao/PostgreSQL 
    networks:
      - postgres-compose-network
    

networks: 
  postgres-compose-network:
    driver: bridge
